name: flappwrite_ui
description: A new Flutter package project.
version: 0.0.1
homepage: https://dlohani.com.np

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  appwrite: ^4.0.1
  flappwrite_account_kit:
    git: https://github.com/lohanidamodar/flappwrite_account_kit
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
